title: Fu-Yin Cherng
logo: /assets/img/profile_2.jpg
description: Welcom!
intro: I'm a researcher interesting in Human-Computer Interaction, Neuroergonomics, and Data Science.
show_links: true

plugins:
  - jekyll-seo-tag
