title: Fu-Yin Cherng
logo: /assets/img/profile_2.jpg
description: Assistant Professor in Human-Computer Interaction at National Cheng Kung University.
intro: Assistant Professor in Human-Computer Interaction at National Cheng Kung University.
show_links: true

plugins:
  - jekyll-seo-tag
