title: Fu-Yin Cherng
logo: /assets/img/profile_2.jpg
description: Fu-Yin Cherng - Assistant Professor in Human-Computer Interaction at National Chung Cheng University.
intro: Fu-Yin Cherng - Assistant Professor in Human-Computer Interaction at National Chung Cheng University.
show_links: true

plugins:
  - jekyll-seo-tag
